In [38]:
import pandas as pd

In [39]:
df_historical_data = pd.read_csv('uefa_europeancup_historical_data.csv')
df_fixture = pd.read_csv('uefa_europeancup_fixture.csv')

In [40]:
# strip deletes blank spaces at the beginning and at the end
df_fixture['home'] = df_fixture['home'].str.strip()
df_fixture['away'] = df_fixture['away'].str.strip()

In [41]:
df_fixture[df_fixture['home'].isnull()]
# There is no null value so we will not delete any fixture

Empty DataFrame
Columns: [home, score, away, year]
Index: []

In [42]:
# Delete unwanted text from the score column (e.g. a.e.t, or Italy's win on coin toss)
df_historical_data['score'] = df_historical_data['score'].str.replace('[^\d–]', '', regex=True)

In [43]:
df_historical_data['home'] = df_historical_data['home'].str.strip()
df_historical_data['away'] = df_historical_data['away'].str.strip()

In [44]:
# Separate score column into HomeGoals and AwayGoals
df_historical_data[['HomeGoals', 'AwayGoals']] = df_historical_data['score'].str.split('–', expand=True)

In [45]:
# Remove score column
df_historical_data.drop('score', axis=1, inplace=True)

In [46]:
# inplace=True to update the dataframe. We could also assign it to the df_historical_data variable
df_historical_data.rename(columns={'home': 'HomeTeam', 'away': 'AwayTeam', 'year': 'Year'}, inplace=True)

# Convert HomeGoals to integer values (they were object type)
df_historical_data = df_historical_data.astype({'HomeGoals': int, 'AwayGoals': int, 'Year': int})

In [47]:
df_historical_data.dtypes

HomeTeam     object
AwayTeam     object
Year          int64
HomeGoals     int64
AwayGoals     int64
dtype: object

In [48]:
# New column that adds home and away goals
df_historical_data['TotalGoals'] = df_historical_data['HomeGoals'] + df_historical_data['AwayGoals']

In [49]:
# Exporting clean dataframes
df_historical_data.to_csv('clean_uefa_europeancup_historical_data.csv', index=False)
df_fixture.to_csv('clean_uefa_europeancup_fixture.csv', index=False)

In [50]:
# Extra verifications to check the number of matches played in each edition
years = [1960, 1964, 1968, 1972,1976, 1980, 1984, 1988,
         1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]

for year in years:
  print(year, len(df_historical_data[df_historical_data['Year'] == year]))

1960 4
1964 4
1968 5
1972 4
1976 4
1980 14
1984 15
1988 15
1992 15
1996 31
2000 31
2004 31
2008 31
2012 31
2016 51
2020 51